package rw.ac.auca.model;

public enum EAcademicUnit {
    PROGRAMME,
    FACULTY,
    DEPARTMENT,
    UNDERGRADUATE,
    MASTERS,
    INFORMATION_TECHNOLOGY,
    BUSINESS,

    SOFTWARE_ENGINEERING,
    INFORMATION_MANAGEMENT,
    BIG_DATA_ANALYTICS,
    ACCOUNTING,
    MANAGEMENT;

}
